"""
Configuration globale de l'application Suno Downloader
"""

# Application
APP_NAME = "🎵 Suno Downloader"
APP_VERSION = "2.0"
DEFAULT_WIDTH = 1500
DEFAULT_HEIGHT = 850
DEFAULT_LANGUAGE = "Français"

# Fichiers
COOKIES_FILE = "suno_cookies.json"

# 📁 CHEMINS DE STOCKAGE
MUSIK_LIBRARY_PATH = r"D:\Musik"
DOWNLOADS_PATH = "downloads"
TEMP_CACHE_PATH = "downloads/!temp"  # ⭐ Cache dans downloads
LANGUAGES_PATH = "languages"

# API
SUNO_BASE_URL = "https://studio-api.prod.suno.com"
DEFAULT_DEVICE_ID = "8f955be9-40b8-496e-9a05-c12b86abd5f8"

# Interface
TOOLBAR_HEIGHT = 50
LOG_HEIGHT = 6
TREE_ROW_HEIGHT = 24

# 🎨 THÈME SUNO
COLOR_SUNO_YELLOW = "#FEB403"
COLOR_SUNO_PINK = "#FF3E7E"
COLOR_SUNO_ORANGE = "#FB5D22"

COLOR_PRIMARY = "#1a1a2e"
COLOR_SECONDARY = "#16213e"
COLOR_DARK_BG = "#0f0f1e"
COLOR_CARD_BG = "#252538"

COLOR_SUCCESS = "#00d9a3"
COLOR_WARNING = COLOR_SUNO_ORANGE
COLOR_DANGER = COLOR_SUNO_PINK
COLOR_INFO = COLOR_SUNO_YELLOW

COLOR_TEXT_LIGHT = "#e4e4e7"
COLOR_TEXT_MUTED = "#a1a1aa"
COLOR_BORDER = "#3f3f46"